<?php
include 'mokiniai.php';
?>
<link rel="stylesheet" href="styles.css">
<table style="width:100%">
  <tr>
    <th>Klase</th>
    <th>Kodas</th>
    <th>Vardas</th>
    <th>Pavarde</th>
    <th>Kontroliniu darbu vidurkis</th>
    <th>Duomenu formavimo data</th>
  </tr>
  <tr>
    <td><?=$klase[0]?></td>
    <td><?=$kodas?></td>
    <td><?=$name[0]?></td>
    <td><?=$lastname[0]?></td>
    <td><?=$vidurkis?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[1]?></td>
    <td><?=$kodas1?></td>
    <td><?=$name[1]?></td>
    <td><?=$lastname[1]?></td>
    <td><?=$vidurkis1?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[2]?></td>
    <td><?=$kodas2?></td>
    <td><?=$name[2]?></td>
    <td><?=$lastname[2]?></td>
    <td><?=$vidurkis2?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[3]?></td>
    <td><?=$kodas3?></td>
    <td><?=$name[3]?></td>
    <td><?=$lastname[3]?></td>
    <td><?=$vidurkis3?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[4]?></td>
    <td><?=$kodas4?></td>
    <td><?=$name[4]?></td>
    <td><?=$lastname[4]?></td>
    <td><?=$vidurkis4?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[5]?></td>
    <td><?=$kodas5?></td>
    <td><?=$name[5]?></td>
    <td><?=$lastname[5]?></td>
    <td><?=$vidurkis5?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[6]?></td>
    <td><?=$kodas6?></td>
    <td><?=$name[6]?></td>
    <td><?=$lastname[6]?></td>
    <td><?=$vidurkis6?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[7]?></td>
    <td><?=$kodas7?></td>
    <td><?=$name[7]?></td>
    <td><?=$lastname[7]?></td>
    <td><?=$vidurkis7?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[8]?></td>
    <td><?=$kodas8?></td>
    <td><?=$name[8]?></td>
    <td><?=$lastname[8]?></td>
    <td><?=$vidurkis8?></td>
    <td><?=$date?></td>
  </tr>
  <tr>
    <td><?=$klase[9]?></td>
    <td><?=$kodas9?></td>
    <td><?=$name[9]?></td>
    <td><?=$lastname[9]?></td>
    <td><?=$vidurkis9?></td>
    <td><?=$date?></td>
  </tr>
</table>